### ISSUE TITLE
6 hours of reindexing. 100% CPU load. No result

### ISSUE THREAD

**Issue by knnk07** [zobo/vscode-php-intellisense#40]
VSCode running in server mode.

It is reindexing the same files again and again... it is wierd.
It is better to switch it off. But there is no option other than uninstall it...

And It leaves dead threads after closing VSCode...

**Comment by zobo** [comment]
Hi.
Sorry for the late answer. This could be a known error. It sometimes happens that there is a directory reading error and instead of skipping that part, it fails completely. I have it on my radar.
One related task: https://github.com/zobo/php-language-server/issues/6

**Comment by tcampbPPU** [comment]
Similar is happening to me, my `vendor` is kept trying to index, I am on:
```
OS: Ubuntu 20.04.4 LTS x86_64
PHP 8.1
VS Code: 1.66.2
```

**Comment by leonardoMoliveira** [comment]
Same problem here.

**Comment by Keller18306** [comment]
The same (VSCode Session with Remote SSH)
![image](https://user-images.githubusercontent.com/23178771/218285775-62767be5-8946-4fb9-99fc-12a40d82a048.png)

**Comment by zobo** [comment]
Hi. Do you have 17878 files in your project? Or are you opening / or some top level folder? If so, try opening your project folder instead. 
If the counter keeps restarting look at the vscode panel, output, then select php language server and see if there is any crash info. 
Best.

**Comment by Keller18306** [comment]
![image](https://user-images.githubusercontent.com/23178771/218316713-14ab6b9b-d395-44ce-bb06-5a614e83dd8f.png)

**Comment by Keller18306** [comment]
![image](https://user-images.githubusercontent.com/23178771/218316752-da491d17-5922-40b6-9026-e2538e25f742.png)
Files from /internal_data/ should not be verified, because they are generated automatically. Is it possible to add a path to ignore?

**Comment by Keller18306** [comment]
![image](https://user-images.githubusercontent.com/23178771/218318163-dfd6631e-8d89-4107-9e47-5202f68cffbc.png)

**Comment by zobo** [comment]
I've implemented #60, please update to 1.1.0 and see setting `php.files.exclude`. Let me know if it works ok. You would probably set something like this
`"php.files.exclude":["internal_data/**"]`

**Comment by Keller18306** [comment]
Why closed.  Although fewer files will be checked, the fact that it checks every time it starts is also a problem.

**Comment by zobo** [comment]
Yes sorry. I'd say it's a dup of #14. I plan to rework the indexing and cache system, just hard to find time to get to it.
Ideally I want to use something like sqlite to store and access index data, but I can't rely on it as the local PHP instance could be without support.

**Comment by Keller18306** [comment]
> I've implemented #60, please update to 1.1.0 and see setting `php.files.exclude`. Let me know if it works ok. You would probably set something like this `"php.files.exclude":["internal_data/**"]`

![image](https://user-images.githubusercontent.com/23178771/218830983-c5d761ca-67e1-48ac-ae15-3f12e96e70ef.png)
doesn't work

**Comment by Keller18306** [comment]
![image](https://user-images.githubusercontent.com/23178771/218831299-7c539883-82cb-43c1-a056-88e45f8edca1.png)
probably PHP doesn't updated

**Comment by Keller18306** [comment]
I'll probably stop using this extension. Useless index. Classes still does not prompt

**Comment by zobo** [comment]
Hm. Can you try to put the setting in your work folder .vscode?
Also. When it starts indexing there will be a line that says how many files will be indexed and how many files "unfiltered" it would be.
I have an idea how to change indexing so it would be properly cached even for the "local" project files.

**Comment by zobo** [comment]
I gave you wrong info, sorry about that. The glob pattern should be like this:
```json
{
	"php.files.exclude": ["internal_data/**/*"]
}
```
There is an output like this on top of the log that should make it obvious if it works or not:
`[Info  - 12:44:32 PM] 1134 files total (unfiltered 1141)`

**Comment by semsion** [comment]
> I gave you wrong info, sorry about that. The glob pattern should be like this:
> 
> ```json
> {
> 	"php.files.exclude": ["internal_data/**/*"]
> }
> ```
> 
> There is an output like this on top of the log that should make it obvious if it works or not: `[Info - 12:44:32 PM] 1134 files total (unfiltered 1141)`

For anyone wondering, this will exclude a directory called internal_data, any files or directories within the internal_data directory, and any file or directory name within the specified path.
