### ISSUE TITLE
Extension issue```json  { 	"messages": [], 	"activationTimes": { 		"codeLoadingTime": 3883, 		"activateCallTime": 11, 		"activateResolvedTime": 94, 		"activationReason": { 			"startup": false, 			"extensionId": { 				"value": "zobo.php-intellisense", 				"_lower": "zobo.php-intellisense" 			}, 			"activationEvent": "onLanguage:php" 		} 	}, 	"runtimeErrors": [], 	"runningLocation": { 		"affinity": 0, 		"kind": 1 	} } ```

### ISSUE THREAD

**Issue by Halcooo** [zobo/vscode-php-intellisense#51]
- Issue Type: `Bug`
- Extension Name: `php-intellisense`
- Extension Version: `1.0.11`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zobo** [comment]
There is no provided data. Please state the PHP version and output of Output / PHP Language Server.
