### ISSUE TITLE
go to definition not showing in menu

### ISSUE THREAD

**Issue by daslicht** [zobo/vscode-php-intellisense#53]
go to definition not showing in menu:
![](https://i.imgur.com/pHc06xT.png)
idea what coudl be wrong ?

**Comment by zobo** [comment]
I don't think this is correctly implemented.. Opened and issue: https://github.com/zobo/php-language-server/issues/27

**Comment by daslicht** [comment]
I managed to get it show up meanwhile, but it has no function :)

**Comment by daslicht** [comment]
hgmn condecompletion isnt working at all on my remote project. Not even in teh same class :/

**Comment by zobo** [comment]
I can use vscode remote and this extension just fine. Check the Panel, Output and then select PHP Language Server on the right. See if there is any output.

See if it helps if you set the `php.executablePath` setting (but be sure to select either remote, remote user or project local).
