### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by lelonkala** [zobo/vscode-php-intellisense#54]
- Issue Type: `Bug`
- Extension Name: `php-intellisense`
- Extension Version: `1.0.11`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zobo** [comment]
There is no provided data. Please state the PHP version and output of Output / PHP Language Server.
