### ISSUE TITLE
an error tips of php version 

### ISSUE THREAD

**Issue by SkyCheung** [zobo/vscode-php-intellisense#6]
if (semver.lt(version, composerJson.config.platform.php)) {
        vscode.window.showErrorMessage(
            'The language server needs at least PHP 7.1 installed. Version found: ' + version
        )
        return
    }

if (semver.lt(version, composerJson.config.platform.php)) {
        vscode.window.showErrorMessage(
            'The language server needs at least PHP '**+composerJson.config.platform.php+** ' installed. Version found: ' + version
        )
        return
    }

**Comment by zobo** [comment]
Hi!

You are right! This makes sense!
