### ISSUE TITLE
An error occurs after version 1.3 is upgraded

### ISSUE THREAD

**Issue by Lw2xy** [zobo/vscode-php-intellisense#67]
DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The Xdebug extension is not loaded

[Error - 11:08:05] Server initialization failed.
  Message: ParseError: syntax error, unexpected ')', expecting variable (T_VARIABLE) in /Users/ee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/felixfbecker/language-server-protocol/src/TextDocumentClientCapabilities.php:247
Stack trace:
#0 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/Users/eee/...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('LanguageServerP...')
#2 [internal function]: spl_autoload_call('LanguageServerP...')
#3 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/netresearch/jsonmapper/src/JsonMapper.php(258): is_a('\\LanguageServer...', 'ArrayObject', true)
#4 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(136): JsonMapper->map(Object(stdClass), Object(LanguageServerProtocol\ClientCapabilities))
#5 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/felixfbecker/language-server/src/LanguageServer.php(149): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#6 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#7 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/sabre/event/lib/coroutine.php(70): Generator->valid()
#8 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/sabre/event/lib/coroutine.php(117): Sabre\Event\{closure}()
#9 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/felixfbecker/language-server/src/LanguageServer.php(172): Sabre\Event\coroutine(Object(Closure))
#10 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/sabre/event/lib/EmitterTrait.php(80): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Message))
#11 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/felixfbecker/language-server/src/ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#12 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/sabre/event/lib/Loop/Loop.php(283): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#13 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/sabre/event/lib/Loop/Loop.php(210): Sabre\Event\Loop\Loop->runStreams(NULL)
#14 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/sabre/event/lib/Loop/Loop.php(173): Sabre\Event\Loop\Loop->tick(true)
#15 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/sabre/event/lib/Loop/functions.php(102): Sabre\Event\Loop\Loop->run()
#16 /Users/eee/.vscode/extensions/zobo.php-intellisense-1.3.0/vendor/felixfbecker/language-server/bin/php-language-server.php(59): Sabre\Event\Loop\run()

**Comment by zobo** [comment]
Oh. What PHP are you running on? Will fix it asap.

**Comment by Lw2xy** [comment]
> 哦。你运行在什么 PHP 上？会尽快修复它。

There is no problem with php 7.4.33 falling back to the 1.2 version. I hope to fix the 1.3 version as soon as possible

**Comment by zobo** [comment]
I added checks https://github.com/zobo/php-language-server-protocol/pull/3 and a fix will be released shortly.

**Comment by Lw2xy** [comment]
> 我添加了检查[zobo/php-language-server-protocol#3](https://github.com/zobo/php-language-server-protocol/pull/3)并且很快就会发布修复程序。

thinks

**Comment by Lw2xy** [comment]
> I added checks [zobo/php-language-server-protocol#3](https://github.com/zobo/php-language-server-protocol/pull/3) and a fix will be released shortly.

Issue resolved after update，666～

**Comment by mrleemon** [comment]
After updating to 1.3.1, I no longer see the error the OP reported. Thanks.
