### ISSUE TITLE
What's the difference between this one and bmewburn/vscode-intelephense

### ISSUE THREAD

**Issue by liudonghua123** [zobo/vscode-php-intellisense#69]
Hi, I am new to php, I use vscode a lot. When I start to learn PHP recently, I found two PHP IntelliSense extension on the market. 

- [PHP IntelliSense](https://marketplace.visualstudio.com/items?itemName=zobo.php-intellisense), https://github.com/zobo/vscode-php-intellisense
- [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client), https://github.com/bmewburn/vscode-intelephense

Both of them provided PHP code intelligence for Visual Studio Code.

And [PHP Extension Pack](https://marketplace.visualstudio.com/items?itemName=xdebug.php-pack) includes [PHP IntelliSense](https://marketplace.visualstudio.com/items?itemName=zobo.php-intellisense), while [PHP Pack](https://marketplace.visualstudio.com/items?itemName=JustPlayer.justins-php-pack) includes [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client).

What's the difference between them?

**Comment by zobo** [comment]
They both provide "PHP language services" to VS Code. IntelliSense is an old extension that I try to maintain and extend when possible. Intelephense is from a different author. It has a free/commercial model. There is also DEVSENSE - but that one conflicts with PHP Debug extension. There is also https://github.com/phpactor/vscode-phpactor but that is not yet on the marketplace (but will be in a few days)

**Comment by zobo** [comment]
See https://marketplace.visualstudio.com/items?itemName=phpactor.vscode-phpactor
