### ISSUE TITLE
Extension signature verification failed with error 'ENOENT'

### ISSUE THREAD

**Issue by davidwhthomas** [zobo/vscode-php-intellisense#72]
When installing this extension in VSCode, I get a somewhat ominous error:

`Extension signature verification failed with error 'ENOENT'`

<img width="1001" alt="Screen Shot 2024-02-14 at 1 40 51 PM" src="https://github.com/zobo/vscode-php-intellisense/assets/1858243/e3e84e6c-23d2-4561-9f20-f76b33e57aa7">

**Comment by zobo** [comment]
On what OS are you seeing this? I cant reproduce on Win nor Linux.
There were cases where the downloaded extension had some errors that happened in transit.

Try to install it again, and if it doesn't work try to delete the extension cache. On windows its in `C:\Users\xxx\AppData\Local\Temp\vsch\extensionsCache\zobo.php-intellisense-*`. Or just try to search for `*php-intellisese*` in your user home folder.

Then try to install the extension again.

Alternatively you can try to download it directly from the marketplace (https://marketplace.visualstudio.com/items?itemName=zobo.php-intellisense Download Extension) and install it from that file:

![image](https://github.com/zobo/vscode-php-intellisense/assets/2456026/5e25559d-4824-4c26-9160-146c1ada01d1)

Good luck.

**Comment by davidwhthomas** [comment]
Hi there,

Thanks for your reply.

I was installaing the extension on a remote ssh ubuntu linux server from VSCode.

However, I can't seem to replicate the issue when uninstalling and reinstalling the extension so I'm assume it was just a temporary error and ok now, thanks again.
