### ISSUE TITLE
Can cache index files be supported?

### ISSUE THREAD

**Issue by qymeng95** [zobo/vscode-php-intellisense#74]
Every time I reopen the project, the project files will be re-indexed. Is it possible to support caching the index files to the host? After reopening the project, I can directly load the cached file index.

**Comment by zobo** [comment]
Instarted working on this, but got stuck with some architectural problems. No telling when I'll be able to get to it again. 
If you are on mac/linux give phpactor a try.

**Comment by qymeng95** [comment]
Thanks for your suggestion, I will try it. And thank you for your work in developing and maintaining the plugin.
